//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.31 at 05:59:11 PM IST 
//


package webmail.wsdlnew;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArrayOfInboxMailQuickSearch complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfInboxMailQuickSearch"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="InboxMailListQuickSearch" type="{http://webmail.com/Search}InboxQuickSearch" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfInboxMailQuickSearch", namespace = "http://webmail.com/Search", propOrder = {
    "inboxMailListQuickSearch"
})
public class ArrayOfInboxMailQuickSearch {

    @XmlElement(name = "InboxMailListQuickSearch", nillable = true)
    protected List<InboxQuickSearch> inboxMailListQuickSearch;

    /**
     * Gets the value of the inboxMailListQuickSearch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inboxMailListQuickSearch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInboxMailListQuickSearch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InboxQuickSearch }
     * 
     * 
     */
    public List<InboxQuickSearch> getInboxMailListQuickSearch() {
        if (inboxMailListQuickSearch == null) {
            inboxMailListQuickSearch = new ArrayList<InboxQuickSearch>();
        }
        return this.inboxMailListQuickSearch;
    }

}
