//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.31 at 05:59:11 PM IST 
//


package webmail.wsdlnew;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="response" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *         &lt;element name="eventuid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="eventcolor" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="repeatdates" type="{http://webmail.com/calendar}DateTimeList"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "response",
    "eventuid",
    "eventcolor",
    "repeatdates"
})
@XmlRootElement(name = "createEventResponse", namespace = "http://webmail.com/calendar")
public class CreateEventResponse {

    @XmlElement(namespace = "http://webmail.com/calendar", required = true)
    protected byte[] response;
    @XmlElement(namespace = "http://webmail.com/calendar", required = true)
    protected String eventuid;
    @XmlElement(namespace = "http://webmail.com/calendar", required = true)
    protected String eventcolor;
    @XmlElement(namespace = "http://webmail.com/calendar", required = true)
    protected DateTimeList repeatdates;

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setResponse(byte[] value) {
        this.response = value;
    }

    /**
     * Gets the value of the eventuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventuid() {
        return eventuid;
    }

    /**
     * Sets the value of the eventuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventuid(String value) {
        this.eventuid = value;
    }

    /**
     * Gets the value of the eventcolor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventcolor() {
        return eventcolor;
    }

    /**
     * Sets the value of the eventcolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventcolor(String value) {
        this.eventcolor = value;
    }

    /**
     * Gets the value of the repeatdates property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeList }
     *     
     */
    public DateTimeList getRepeatdates() {
        return repeatdates;
    }

    /**
     * Sets the value of the repeatdates property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeList }
     *     
     */
    public void setRepeatdates(DateTimeList value) {
        this.repeatdates = value;
    }

}
