//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.31 at 05:59:11 PM IST 
//


package webmail.wsdlnew;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="webamilIp" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="webamilId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="webamilPassword" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="webamilFromName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="webamilHost" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="webamilPort" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="webamilIMAPPort" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="webamilSaveSent" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="webamilTo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="webamilCc" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="webamilBcc" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="webamilSubject" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="webamilBodyContent" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="webamilPriority" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="webamilReadRec" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="webmailDraftUid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="webamilAttach" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="webmailTextType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="webmailXMailer" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="webmailOldMessageID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="webmailReferences" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="AttachmentFileName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="AttachmentFileNewName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "webamilIp",
    "webamilId",
    "webamilPassword",
    "webamilFromName",
    "webamilHost",
    "webamilPort",
    "webamilIMAPPort",
    "webamilSaveSent",
    "webamilTo",
    "webamilCc",
    "webamilBcc",
    "webamilSubject",
    "webamilBodyContent",
    "webamilPriority",
    "webamilReadRec",
    "webmailDraftUid",
    "webamilAttach",
    "webmailTextType",
    "webmailXMailer",
    "webmailOldMessageID",
    "webmailReferences",
    "attachmentFileName",
    "attachmentFileNewName"
})
@XmlRootElement(name = "getComposeMailRequest", namespace = "http://webmail.com/Compose")
public class GetComposeMailRequest {

    @XmlElement(namespace = "http://webmail.com/Compose", required = true)
    protected String webamilIp;
    @XmlElement(namespace = "http://webmail.com/Compose", required = true)
    protected String webamilId;
    @XmlElement(namespace = "http://webmail.com/Compose", required = true)
    protected String webamilPassword;
    @XmlElement(namespace = "http://webmail.com/Compose", required = true)
    protected String webamilFromName;
    @XmlElement(namespace = "http://webmail.com/Compose", required = true)
    protected String webamilHost;
    @XmlElement(namespace = "http://webmail.com/Compose", required = true)
    protected String webamilPort;
    @XmlElement(namespace = "http://webmail.com/Compose", required = true)
    protected String webamilIMAPPort;
    @XmlElement(namespace = "http://webmail.com/Compose")
    protected boolean webamilSaveSent;
    @XmlElement(namespace = "http://webmail.com/Compose", required = true)
    protected String webamilTo;
    @XmlElement(namespace = "http://webmail.com/Compose", required = true)
    protected String webamilCc;
    @XmlElement(namespace = "http://webmail.com/Compose", required = true)
    protected String webamilBcc;
    @XmlElement(namespace = "http://webmail.com/Compose", required = true)
    protected String webamilSubject;
    @XmlElement(namespace = "http://webmail.com/Compose", required = true)
    protected String webamilBodyContent;
    @XmlElement(namespace = "http://webmail.com/Compose", required = true)
    protected String webamilPriority;
    @XmlElement(namespace = "http://webmail.com/Compose", required = true)
    protected String webamilReadRec;
    @XmlElement(namespace = "http://webmail.com/Compose", required = true)
    protected String webmailDraftUid;
    @XmlElement(namespace = "http://webmail.com/Compose")
    protected boolean webamilAttach;
    @XmlElement(namespace = "http://webmail.com/Compose", required = true)
    protected String webmailTextType;
    @XmlElement(namespace = "http://webmail.com/Compose", required = true)
    protected String webmailXMailer;
    @XmlElement(namespace = "http://webmail.com/Compose", required = true)
    protected String webmailOldMessageID;
    @XmlElement(namespace = "http://webmail.com/Compose", required = true)
    protected String webmailReferences;
    @XmlElement(name = "AttachmentFileName", namespace = "http://webmail.com/Compose")
    protected List<String> attachmentFileName;
    @XmlElement(name = "AttachmentFileNewName", namespace = "http://webmail.com/Compose")
    protected List<String> attachmentFileNewName;

    /**
     * Gets the value of the webamilIp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebamilIp() {
        return webamilIp;
    }

    /**
     * Sets the value of the webamilIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebamilIp(String value) {
        this.webamilIp = value;
    }

    /**
     * Gets the value of the webamilId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebamilId() {
        return webamilId;
    }

    /**
     * Sets the value of the webamilId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebamilId(String value) {
        this.webamilId = value;
    }

    /**
     * Gets the value of the webamilPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebamilPassword() {
        return webamilPassword;
    }

    /**
     * Sets the value of the webamilPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebamilPassword(String value) {
        this.webamilPassword = value;
    }

    /**
     * Gets the value of the webamilFromName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebamilFromName() {
        return webamilFromName;
    }

    /**
     * Sets the value of the webamilFromName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebamilFromName(String value) {
        this.webamilFromName = value;
    }

    /**
     * Gets the value of the webamilHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebamilHost() {
        return webamilHost;
    }

    /**
     * Sets the value of the webamilHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebamilHost(String value) {
        this.webamilHost = value;
    }

    /**
     * Gets the value of the webamilPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebamilPort() {
        return webamilPort;
    }

    /**
     * Sets the value of the webamilPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebamilPort(String value) {
        this.webamilPort = value;
    }

    /**
     * Gets the value of the webamilIMAPPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebamilIMAPPort() {
        return webamilIMAPPort;
    }

    /**
     * Sets the value of the webamilIMAPPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebamilIMAPPort(String value) {
        this.webamilIMAPPort = value;
    }

    /**
     * Gets the value of the webamilSaveSent property.
     * 
     */
    public boolean isWebamilSaveSent() {
        return webamilSaveSent;
    }

    /**
     * Sets the value of the webamilSaveSent property.
     * 
     */
    public void setWebamilSaveSent(boolean value) {
        this.webamilSaveSent = value;
    }

    /**
     * Gets the value of the webamilTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebamilTo() {
        return webamilTo;
    }

    /**
     * Sets the value of the webamilTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebamilTo(String value) {
        this.webamilTo = value;
    }

    /**
     * Gets the value of the webamilCc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebamilCc() {
        return webamilCc;
    }

    /**
     * Sets the value of the webamilCc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebamilCc(String value) {
        this.webamilCc = value;
    }

    /**
     * Gets the value of the webamilBcc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebamilBcc() {
        return webamilBcc;
    }

    /**
     * Sets the value of the webamilBcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebamilBcc(String value) {
        this.webamilBcc = value;
    }

    /**
     * Gets the value of the webamilSubject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebamilSubject() {
        return webamilSubject;
    }

    /**
     * Sets the value of the webamilSubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebamilSubject(String value) {
        this.webamilSubject = value;
    }

    /**
     * Gets the value of the webamilBodyContent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebamilBodyContent() {
        return webamilBodyContent;
    }

    /**
     * Sets the value of the webamilBodyContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebamilBodyContent(String value) {
        this.webamilBodyContent = value;
    }

    /**
     * Gets the value of the webamilPriority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebamilPriority() {
        return webamilPriority;
    }

    /**
     * Sets the value of the webamilPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebamilPriority(String value) {
        this.webamilPriority = value;
    }

    /**
     * Gets the value of the webamilReadRec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebamilReadRec() {
        return webamilReadRec;
    }

    /**
     * Sets the value of the webamilReadRec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebamilReadRec(String value) {
        this.webamilReadRec = value;
    }

    /**
     * Gets the value of the webmailDraftUid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebmailDraftUid() {
        return webmailDraftUid;
    }

    /**
     * Sets the value of the webmailDraftUid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebmailDraftUid(String value) {
        this.webmailDraftUid = value;
    }

    /**
     * Gets the value of the webamilAttach property.
     * 
     */
    public boolean isWebamilAttach() {
        return webamilAttach;
    }

    /**
     * Sets the value of the webamilAttach property.
     * 
     */
    public void setWebamilAttach(boolean value) {
        this.webamilAttach = value;
    }

    /**
     * Gets the value of the webmailTextType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebmailTextType() {
        return webmailTextType;
    }

    /**
     * Sets the value of the webmailTextType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebmailTextType(String value) {
        this.webmailTextType = value;
    }

    /**
     * Gets the value of the webmailXMailer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebmailXMailer() {
        return webmailXMailer;
    }

    /**
     * Sets the value of the webmailXMailer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebmailXMailer(String value) {
        this.webmailXMailer = value;
    }

    /**
     * Gets the value of the webmailOldMessageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebmailOldMessageID() {
        return webmailOldMessageID;
    }

    /**
     * Sets the value of the webmailOldMessageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebmailOldMessageID(String value) {
        this.webmailOldMessageID = value;
    }

    /**
     * Gets the value of the webmailReferences property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebmailReferences() {
        return webmailReferences;
    }

    /**
     * Sets the value of the webmailReferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebmailReferences(String value) {
        this.webmailReferences = value;
    }

    /**
     * Gets the value of the attachmentFileName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attachmentFileName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttachmentFileName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAttachmentFileName() {
        if (attachmentFileName == null) {
            attachmentFileName = new ArrayList<String>();
        }
        return this.attachmentFileName;
    }

    /**
     * Gets the value of the attachmentFileNewName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attachmentFileNewName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttachmentFileNewName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAttachmentFileNewName() {
        if (attachmentFileNewName == null) {
            attachmentFileNewName = new ArrayList<String>();
        }
        return this.attachmentFileNewName;
    }

}
