//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.31 at 05:59:11 PM IST 
//


package webmail.wsdlnew;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="fromfilecontent" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *         &lt;element name="tofilecontent" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fromfilecontent",
    "tofilecontent"
})
@XmlRootElement(name = "importCalendarRequest", namespace = "http://webmail.com/calendar")
public class ImportCalendarRequest {

    @XmlElement(namespace = "http://webmail.com/calendar", required = true)
    protected byte[] fromfilecontent;
    @XmlElement(namespace = "http://webmail.com/calendar", required = true)
    protected byte[] tofilecontent;

    /**
     * Gets the value of the fromfilecontent property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getFromfilecontent() {
        return fromfilecontent;
    }

    /**
     * Sets the value of the fromfilecontent property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setFromfilecontent(byte[] value) {
        this.fromfilecontent = value;
    }

    /**
     * Gets the value of the tofilecontent property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getTofilecontent() {
        return tofilecontent;
    }

    /**
     * Sets the value of the tofilecontent property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setTofilecontent(byte[] value) {
        this.tofilecontent = value;
    }

}
