//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.31 at 05:59:11 PM IST 
//


package webmail.wsdlnew;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the webmail.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: webmail.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateCalendarRequest }
     * 
     */
    public CreateCalendarRequest createCreateCalendarRequest() {
        return new CreateCalendarRequest();
    }

    /**
     * Create an instance of {@link CreateCalendarResponse }
     * 
     */
    public CreateCalendarResponse createCreateCalendarResponse() {
        return new CreateCalendarResponse();
    }

    /**
     * Create an instance of {@link ImportCalendarRequest }
     * 
     */
    public ImportCalendarRequest createImportCalendarRequest() {
        return new ImportCalendarRequest();
    }

    /**
     * Create an instance of {@link CreateEventRequest }
     * 
     */
    public CreateEventRequest createCreateEventRequest() {
        return new CreateEventRequest();
    }

    /**
     * Create an instance of {@link EventBean }
     * 
     */
    public EventBean createEventBean() {
        return new EventBean();
    }

    /**
     * Create an instance of {@link ChangeColorRequest }
     * 
     */
    public ChangeColorRequest createChangeColorRequest() {
        return new ChangeColorRequest();
    }

    /**
     * Create an instance of {@link ChangeColorResponse }
     * 
     */
    public ChangeColorResponse createChangeColorResponse() {
        return new ChangeColorResponse();
    }

    /**
     * Create an instance of {@link EventArray }
     * 
     */
    public EventArray createEventArray() {
        return new EventArray();
    }

    /**
     * Create an instance of {@link CreateEventResponse }
     * 
     */
    public CreateEventResponse createCreateEventResponse() {
        return new CreateEventResponse();
    }

    /**
     * Create an instance of {@link DateTimeList }
     * 
     */
    public DateTimeList createDateTimeList() {
        return new DateTimeList();
    }

    /**
     * Create an instance of {@link GetEventsRequest }
     * 
     */
    public GetEventsRequest createGetEventsRequest() {
        return new GetEventsRequest();
    }

    /**
     * Create an instance of {@link GetEventsResponse }
     * 
     */
    public GetEventsResponse createGetEventsResponse() {
        return new GetEventsResponse();
    }

    /**
     * Create an instance of {@link GetFilterEventsRequest }
     * 
     */
    public GetFilterEventsRequest createGetFilterEventsRequest() {
        return new GetFilterEventsRequest();
    }

    /**
     * Create an instance of {@link GetFilterEventsResponse }
     * 
     */
    public GetFilterEventsResponse createGetFilterEventsResponse() {
        return new GetFilterEventsResponse();
    }

    /**
     * Create an instance of {@link GeteventdetailsRequest }
     * 
     */
    public GeteventdetailsRequest createGeteventdetailsRequest() {
        return new GeteventdetailsRequest();
    }

    /**
     * Create an instance of {@link GeteventdetailsResponse }
     * 
     */
    public GeteventdetailsResponse createGeteventdetailsResponse() {
        return new GeteventdetailsResponse();
    }

    /**
     * Create an instance of {@link GetDeleteEventRequest }
     * 
     */
    public GetDeleteEventRequest createGetDeleteEventRequest() {
        return new GetDeleteEventRequest();
    }

    /**
     * Create an instance of {@link GetDeleteEventResponse }
     * 
     */
    public GetDeleteEventResponse createGetDeleteEventResponse() {
        return new GetDeleteEventResponse();
    }

    /**
     * Create an instance of {@link GetCalendarDetailRequest }
     * 
     */
    public GetCalendarDetailRequest createGetCalendarDetailRequest() {
        return new GetCalendarDetailRequest();
    }

    /**
     * Create an instance of {@link GetCalendarDetailResponse }
     * 
     */
    public GetCalendarDetailResponse createGetCalendarDetailResponse() {
        return new GetCalendarDetailResponse();
    }

    /**
     * Create an instance of {@link CalendarBean }
     * 
     */
    public CalendarBean createCalendarBean() {
        return new CalendarBean();
    }

    /**
     * Create an instance of {@link GetUpdateCalendarRequest }
     * 
     */
    public GetUpdateCalendarRequest createGetUpdateCalendarRequest() {
        return new GetUpdateCalendarRequest();
    }

    /**
     * Create an instance of {@link GetUpdateCalendarResponse }
     * 
     */
    public GetUpdateCalendarResponse createGetUpdateCalendarResponse() {
        return new GetUpdateCalendarResponse();
    }

    /**
     * Create an instance of {@link CreateContactRequest }
     * 
     */
    public CreateContactRequest createCreateContactRequest() {
        return new CreateContactRequest();
    }

    /**
     * Create an instance of {@link CreateContactResponse }
     * 
     */
    public CreateContactResponse createCreateContactResponse() {
        return new CreateContactResponse();
    }

    /**
     * Create an instance of {@link DisplayContactRequest }
     * 
     */
    public DisplayContactRequest createDisplayContactRequest() {
        return new DisplayContactRequest();
    }

    /**
     * Create an instance of {@link GetFullContactDetailResponse }
     * 
     */
    public GetFullContactDetailResponse createGetFullContactDetailResponse() {
        return new GetFullContactDetailResponse();
    }

    /**
     * Create an instance of {@link DisplayContact }
     * 
     */
    public DisplayContact createDisplayContact() {
        return new DisplayContact();
    }

    /**
     * Create an instance of {@link GetLdapFNameRequest }
     * 
     */
    public GetLdapFNameRequest createGetLdapFNameRequest() {
        return new GetLdapFNameRequest();
    }

    /**
     * Create an instance of {@link GetLdapFNameResponse }
     * 
     */
    public GetLdapFNameResponse createGetLdapFNameResponse() {
        return new GetLdapFNameResponse();
    }

    /**
     * Create an instance of {@link GetLdapOneAttOtrUserRequest }
     * 
     */
    public GetLdapOneAttOtrUserRequest createGetLdapOneAttOtrUserRequest() {
        return new GetLdapOneAttOtrUserRequest();
    }

    /**
     * Create an instance of {@link GetLdapOneAttOtrUserResponse }
     * 
     */
    public GetLdapOneAttOtrUserResponse createGetLdapOneAttOtrUserResponse() {
        return new GetLdapOneAttOtrUserResponse();
    }

    /**
     * Create an instance of {@link GetVCFLdapDirRequest }
     * 
     */
    public GetVCFLdapDirRequest createGetVCFLdapDirRequest() {
        return new GetVCFLdapDirRequest();
    }

    /**
     * Create an instance of {@link GetVCFLdapDirResponse }
     * 
     */
    public GetVCFLdapDirResponse createGetVCFLdapDirResponse() {
        return new GetVCFLdapDirResponse();
    }

    /**
     * Create an instance of {@link VCFLdapDirListReturn }
     * 
     */
    public VCFLdapDirListReturn createVCFLdapDirListReturn() {
        return new VCFLdapDirListReturn();
    }

    /**
     * Create an instance of {@link GetContactDetailRequest }
     * 
     */
    public GetContactDetailRequest createGetContactDetailRequest() {
        return new GetContactDetailRequest();
    }

    /**
     * Create an instance of {@link GetContactDetailResponse }
     * 
     */
    public GetContactDetailResponse createGetContactDetailResponse() {
        return new GetContactDetailResponse();
    }

    /**
     * Create an instance of {@link ContactFullDetail }
     * 
     */
    public ContactFullDetail createContactFullDetail() {
        return new ContactFullDetail();
    }

    /**
     * Create an instance of {@link ArrayOfVCFLdapDir }
     * 
     */
    public ArrayOfVCFLdapDir createArrayOfVCFLdapDir() {
        return new ArrayOfVCFLdapDir();
    }

    /**
     * Create an instance of {@link VCFLdapDirAtt }
     * 
     */
    public VCFLdapDirAtt createVCFLdapDirAtt() {
        return new VCFLdapDirAtt();
    }

    /**
     * Create an instance of {@link GetAddTaskRequest }
     * 
     */
    public GetAddTaskRequest createGetAddTaskRequest() {
        return new GetAddTaskRequest();
    }

    /**
     * Create an instance of {@link TaskBean }
     * 
     */
    public TaskBean createTaskBean() {
        return new TaskBean();
    }

    /**
     * Create an instance of {@link GetAddTaskResponse }
     * 
     */
    public GetAddTaskResponse createGetAddTaskResponse() {
        return new GetAddTaskResponse();
    }

    /**
     * Create an instance of {@link GetUpdateTaskRequest }
     * 
     */
    public GetUpdateTaskRequest createGetUpdateTaskRequest() {
        return new GetUpdateTaskRequest();
    }

    /**
     * Create an instance of {@link GetUpdateTaskResponse }
     * 
     */
    public GetUpdateTaskResponse createGetUpdateTaskResponse() {
        return new GetUpdateTaskResponse();
    }

    /**
     * Create an instance of {@link GetTasksRequest }
     * 
     */
    public GetTasksRequest createGetTasksRequest() {
        return new GetTasksRequest();
    }

    /**
     * Create an instance of {@link GetTasksResponse }
     * 
     */
    public GetTasksResponse createGetTasksResponse() {
        return new GetTasksResponse();
    }

    /**
     * Create an instance of {@link TaskArray }
     * 
     */
    public TaskArray createTaskArray() {
        return new TaskArray();
    }

    /**
     * Create an instance of {@link DeleteTaskRequest }
     * 
     */
    public DeleteTaskRequest createDeleteTaskRequest() {
        return new DeleteTaskRequest();
    }

    /**
     * Create an instance of {@link DeleteTaskResponse }
     * 
     */
    public DeleteTaskResponse createDeleteTaskResponse() {
        return new DeleteTaskResponse();
    }

    /**
     * Create an instance of {@link DeleteSelectedTaskRequest }
     * 
     */
    public DeleteSelectedTaskRequest createDeleteSelectedTaskRequest() {
        return new DeleteSelectedTaskRequest();
    }

    /**
     * Create an instance of {@link DeleteSelectedTaskResponse }
     * 
     */
    public DeleteSelectedTaskResponse createDeleteSelectedTaskResponse() {
        return new DeleteSelectedTaskResponse();
    }

    /**
     * Create an instance of {@link GetTaskDetailRequest }
     * 
     */
    public GetTaskDetailRequest createGetTaskDetailRequest() {
        return new GetTaskDetailRequest();
    }

    /**
     * Create an instance of {@link GetTaskDetailResponse }
     * 
     */
    public GetTaskDetailResponse createGetTaskDetailResponse() {
        return new GetTaskDetailResponse();
    }

    /**
     * Create an instance of {@link GetInboxMailSearchRequest }
     * 
     */
    public GetInboxMailSearchRequest createGetInboxMailSearchRequest() {
        return new GetInboxMailSearchRequest();
    }

    /**
     * Create an instance of {@link GetMailInboxSearchResponse }
     * 
     */
    public GetMailInboxSearchResponse createGetMailInboxSearchResponse() {
        return new GetMailInboxSearchResponse();
    }

    /**
     * Create an instance of {@link InboxListReturnSearch }
     * 
     */
    public InboxListReturnSearch createInboxListReturnSearch() {
        return new InboxListReturnSearch();
    }

    /**
     * Create an instance of {@link GetInboxMailQuickSearchRequest }
     * 
     */
    public GetInboxMailQuickSearchRequest createGetInboxMailQuickSearchRequest() {
        return new GetInboxMailQuickSearchRequest();
    }

    /**
     * Create an instance of {@link GetMailInboxQuickSearchResponse }
     * 
     */
    public GetMailInboxQuickSearchResponse createGetMailInboxQuickSearchResponse() {
        return new GetMailInboxQuickSearchResponse();
    }

    /**
     * Create an instance of {@link InboxListReturnQuickSearch }
     * 
     */
    public InboxListReturnQuickSearch createInboxListReturnQuickSearch() {
        return new InboxListReturnQuickSearch();
    }

    /**
     * Create an instance of {@link ArrayOfInboxMailSearch }
     * 
     */
    public ArrayOfInboxMailSearch createArrayOfInboxMailSearch() {
        return new ArrayOfInboxMailSearch();
    }

    /**
     * Create an instance of {@link InboxSearch }
     * 
     */
    public InboxSearch createInboxSearch() {
        return new InboxSearch();
    }

    /**
     * Create an instance of {@link ArrayOfInboxMailQuickSearch }
     * 
     */
    public ArrayOfInboxMailQuickSearch createArrayOfInboxMailQuickSearch() {
        return new ArrayOfInboxMailQuickSearch();
    }

    /**
     * Create an instance of {@link InboxQuickSearch }
     * 
     */
    public InboxQuickSearch createInboxQuickSearch() {
        return new InboxQuickSearch();
    }

    /**
     * Create an instance of {@link GetMailAttachmentRequest }
     * 
     */
    public GetMailAttachmentRequest createGetMailAttachmentRequest() {
        return new GetMailAttachmentRequest();
    }

    /**
     * Create an instance of {@link GetMailAttachmentResponse }
     * 
     */
    public GetMailAttachmentResponse createGetMailAttachmentResponse() {
        return new GetMailAttachmentResponse();
    }

    /**
     * Create an instance of {@link ReplyDisplay }
     * 
     */
    public ReplyDisplay createReplyDisplay() {
        return new ReplyDisplay();
    }

    /**
     * Create an instance of {@link GetWebmailCreateFolderRequest }
     * 
     */
    public GetWebmailCreateFolderRequest createGetWebmailCreateFolderRequest() {
        return new GetWebmailCreateFolderRequest();
    }

    /**
     * Create an instance of {@link GetWebmailCreateFolderResponse }
     * 
     */
    public GetWebmailCreateFolderResponse createGetWebmailCreateFolderResponse() {
        return new GetWebmailCreateFolderResponse();
    }

    /**
     * Create an instance of {@link GetWebmailDeleteFolderRequest }
     * 
     */
    public GetWebmailDeleteFolderRequest createGetWebmailDeleteFolderRequest() {
        return new GetWebmailDeleteFolderRequest();
    }

    /**
     * Create an instance of {@link GetWebmailDeleteFolderResponse }
     * 
     */
    public GetWebmailDeleteFolderResponse createGetWebmailDeleteFolderResponse() {
        return new GetWebmailDeleteFolderResponse();
    }

    /**
     * Create an instance of {@link GetWebmailSubscriptionFolderRequest }
     * 
     */
    public GetWebmailSubscriptionFolderRequest createGetWebmailSubscriptionFolderRequest() {
        return new GetWebmailSubscriptionFolderRequest();
    }

    /**
     * Create an instance of {@link GetWebmailSubscriptionFolderResponse }
     * 
     */
    public GetWebmailSubscriptionFolderResponse createGetWebmailSubscriptionFolderResponse() {
        return new GetWebmailSubscriptionFolderResponse();
    }

    /**
     * Create an instance of {@link GetWebmailFolderRequest }
     * 
     */
    public GetWebmailFolderRequest createGetWebmailFolderRequest() {
        return new GetWebmailFolderRequest();
    }

    /**
     * Create an instance of {@link GetWebmailFolderResponse }
     * 
     */
    public GetWebmailFolderResponse createGetWebmailFolderResponse() {
        return new GetWebmailFolderResponse();
    }

    /**
     * Create an instance of {@link GetWebmailSubFolderRequest }
     * 
     */
    public GetWebmailSubFolderRequest createGetWebmailSubFolderRequest() {
        return new GetWebmailSubFolderRequest();
    }

    /**
     * Create an instance of {@link GetWebmailSubFolderResponse }
     * 
     */
    public GetWebmailSubFolderResponse createGetWebmailSubFolderResponse() {
        return new GetWebmailSubFolderResponse();
    }

    /**
     * Create an instance of {@link GetWebmailFolderOtherRequest }
     * 
     */
    public GetWebmailFolderOtherRequest createGetWebmailFolderOtherRequest() {
        return new GetWebmailFolderOtherRequest();
    }

    /**
     * Create an instance of {@link GetWebmailFolderOtherResponse }
     * 
     */
    public GetWebmailFolderOtherResponse createGetWebmailFolderOtherResponse() {
        return new GetWebmailFolderOtherResponse();
    }

    /**
     * Create an instance of {@link MailFolderListReturn }
     * 
     */
    public MailFolderListReturn createMailFolderListReturn() {
        return new MailFolderListReturn();
    }

    /**
     * Create an instance of {@link GetWebmailFolderSubscribedRequest }
     * 
     */
    public GetWebmailFolderSubscribedRequest createGetWebmailFolderSubscribedRequest() {
        return new GetWebmailFolderSubscribedRequest();
    }

    /**
     * Create an instance of {@link GetWebmailFolderSubscribedResponse }
     * 
     */
    public GetWebmailFolderSubscribedResponse createGetWebmailFolderSubscribedResponse() {
        return new GetWebmailFolderSubscribedResponse();
    }

    /**
     * Create an instance of {@link GetWebmailSubFolderSubscribedRequest }
     * 
     */
    public GetWebmailSubFolderSubscribedRequest createGetWebmailSubFolderSubscribedRequest() {
        return new GetWebmailSubFolderSubscribedRequest();
    }

    /**
     * Create an instance of {@link GetWebmailSubFolderSubscribedResponse }
     * 
     */
    public GetWebmailSubFolderSubscribedResponse createGetWebmailSubFolderSubscribedResponse() {
        return new GetWebmailSubFolderSubscribedResponse();
    }

    /**
     * Create an instance of {@link GetWebmailFolderSubscribedOtherRequest }
     * 
     */
    public GetWebmailFolderSubscribedOtherRequest createGetWebmailFolderSubscribedOtherRequest() {
        return new GetWebmailFolderSubscribedOtherRequest();
    }

    /**
     * Create an instance of {@link GetWebmailFolderSubscribedOtherResponse }
     * 
     */
    public GetWebmailFolderSubscribedOtherResponse createGetWebmailFolderSubscribedOtherResponse() {
        return new GetWebmailFolderSubscribedOtherResponse();
    }

    /**
     * Create an instance of {@link SubsFolderListReturn }
     * 
     */
    public SubsFolderListReturn createSubsFolderListReturn() {
        return new SubsFolderListReturn();
    }

    /**
     * Create an instance of {@link GetWebmailSubFolderSubscribedOtherRequest }
     * 
     */
    public GetWebmailSubFolderSubscribedOtherRequest createGetWebmailSubFolderSubscribedOtherRequest() {
        return new GetWebmailSubFolderSubscribedOtherRequest();
    }

    /**
     * Create an instance of {@link GetWebmailSubFolderSubscribedOtherResponse }
     * 
     */
    public GetWebmailSubFolderSubscribedOtherResponse createGetWebmailSubFolderSubscribedOtherResponse() {
        return new GetWebmailSubFolderSubscribedOtherResponse();
    }

    /**
     * Create an instance of {@link SubsSubFolderListReturn }
     * 
     */
    public SubsSubFolderListReturn createSubsSubFolderListReturn() {
        return new SubsSubFolderListReturn();
    }

    /**
     * Create an instance of {@link ArrayOfMailFolder }
     * 
     */
    public ArrayOfMailFolder createArrayOfMailFolder() {
        return new ArrayOfMailFolder();
    }

    /**
     * Create an instance of {@link MailImapFolders }
     * 
     */
    public MailImapFolders createMailImapFolders() {
        return new MailImapFolders();
    }

    /**
     * Create an instance of {@link ArrayOfSubsFolder }
     * 
     */
    public ArrayOfSubsFolder createArrayOfSubsFolder() {
        return new ArrayOfSubsFolder();
    }

    /**
     * Create an instance of {@link SubsImapFolders }
     * 
     */
    public SubsImapFolders createSubsImapFolders() {
        return new SubsImapFolders();
    }

    /**
     * Create an instance of {@link ArrayOfSubsSubFolder }
     * 
     */
    public ArrayOfSubsSubFolder createArrayOfSubsSubFolder() {
        return new ArrayOfSubsSubFolder();
    }

    /**
     * Create an instance of {@link SubsImapSubFolders }
     * 
     */
    public SubsImapSubFolders createSubsImapSubFolders() {
        return new SubsImapSubFolders();
    }

    /**
     * Create an instance of {@link GetWebmailQuotaRequest }
     * 
     */
    public GetWebmailQuotaRequest createGetWebmailQuotaRequest() {
        return new GetWebmailQuotaRequest();
    }

    /**
     * Create an instance of {@link GetWebmailQuotaResponse }
     * 
     */
    public GetWebmailQuotaResponse createGetWebmailQuotaResponse() {
        return new GetWebmailQuotaResponse();
    }

    /**
     * Create an instance of {@link GetWebmailAuthRequest }
     * 
     */
    public GetWebmailAuthRequest createGetWebmailAuthRequest() {
        return new GetWebmailAuthRequest();
    }

    /**
     * Create an instance of {@link GetWebmailAuthResponse }
     * 
     */
    public GetWebmailAuthResponse createGetWebmailAuthResponse() {
        return new GetWebmailAuthResponse();
    }

    /**
     * Create an instance of {@link GetWebmailImapquotaRequest }
     * 
     */
    public GetWebmailImapquotaRequest createGetWebmailImapquotaRequest() {
        return new GetWebmailImapquotaRequest();
    }

    /**
     * Create an instance of {@link GetWebmailImapquotaResponse }
     * 
     */
    public GetWebmailImapquotaResponse createGetWebmailImapquotaResponse() {
        return new GetWebmailImapquotaResponse();
    }

    /**
     * Create an instance of {@link Imapquota }
     * 
     */
    public Imapquota createImapquota() {
        return new Imapquota();
    }

    /**
     * Create an instance of {@link GetWebmailUnreadMailCountRequest }
     * 
     */
    public GetWebmailUnreadMailCountRequest createGetWebmailUnreadMailCountRequest() {
        return new GetWebmailUnreadMailCountRequest();
    }

    /**
     * Create an instance of {@link GetWebmailUnreadMailCountResponse }
     * 
     */
    public GetWebmailUnreadMailCountResponse createGetWebmailUnreadMailCountResponse() {
        return new GetWebmailUnreadMailCountResponse();
    }

    /**
     * Create an instance of {@link GetWebmailAllMailCountRequest }
     * 
     */
    public GetWebmailAllMailCountRequest createGetWebmailAllMailCountRequest() {
        return new GetWebmailAllMailCountRequest();
    }

    /**
     * Create an instance of {@link GetWebmailAllMailCountResponse }
     * 
     */
    public GetWebmailAllMailCountResponse createGetWebmailAllMailCountResponse() {
        return new GetWebmailAllMailCountResponse();
    }

    /**
     * Create an instance of {@link GetInboxMailRequest }
     * 
     */
    public GetInboxMailRequest createGetInboxMailRequest() {
        return new GetInboxMailRequest();
    }

    /**
     * Create an instance of {@link GetMailInboxResponse }
     * 
     */
    public GetMailInboxResponse createGetMailInboxResponse() {
        return new GetMailInboxResponse();
    }

    /**
     * Create an instance of {@link InboxListReturn }
     * 
     */
    public InboxListReturn createInboxListReturn() {
        return new InboxListReturn();
    }

    /**
     * Create an instance of {@link GetInboxMailDescRequest }
     * 
     */
    public GetInboxMailDescRequest createGetInboxMailDescRequest() {
        return new GetInboxMailDescRequest();
    }

    /**
     * Create an instance of {@link GetMailInboxDescResponse }
     * 
     */
    public GetMailInboxDescResponse createGetMailInboxDescResponse() {
        return new GetMailInboxDescResponse();
    }

    /**
     * Create an instance of {@link InboxListDescReturn }
     * 
     */
    public InboxListDescReturn createInboxListDescReturn() {
        return new InboxListDescReturn();
    }

    /**
     * Create an instance of {@link ArrayOfInboxMail }
     * 
     */
    public ArrayOfInboxMail createArrayOfInboxMail() {
        return new ArrayOfInboxMail();
    }

    /**
     * Create an instance of {@link Inbox }
     * 
     */
    public Inbox createInbox() {
        return new Inbox();
    }

    /**
     * Create an instance of {@link ArrayOfInboxMailDesc }
     * 
     */
    public ArrayOfInboxMailDesc createArrayOfInboxMailDesc() {
        return new ArrayOfInboxMailDesc();
    }

    /**
     * Create an instance of {@link InboxDesc }
     * 
     */
    public InboxDesc createInboxDesc() {
        return new InboxDesc();
    }

    /**
     * Create an instance of {@link GetWebmailMoveTrashRequest }
     * 
     */
    public GetWebmailMoveTrashRequest createGetWebmailMoveTrashRequest() {
        return new GetWebmailMoveTrashRequest();
    }

    /**
     * Create an instance of {@link GetWebmailMoveTrashResponse }
     * 
     */
    public GetWebmailMoveTrashResponse createGetWebmailMoveTrashResponse() {
        return new GetWebmailMoveTrashResponse();
    }

    /**
     * Create an instance of {@link GetWebmailSpamRequest }
     * 
     */
    public GetWebmailSpamRequest createGetWebmailSpamRequest() {
        return new GetWebmailSpamRequest();
    }

    /**
     * Create an instance of {@link GetWebmailSpamResponse }
     * 
     */
    public GetWebmailSpamResponse createGetWebmailSpamResponse() {
        return new GetWebmailSpamResponse();
    }

    /**
     * Create an instance of {@link SetWebmailFlageRequest }
     * 
     */
    public SetWebmailFlageRequest createSetWebmailFlageRequest() {
        return new SetWebmailFlageRequest();
    }

    /**
     * Create an instance of {@link SetWebmailFlagResponse }
     * 
     */
    public SetWebmailFlagResponse createSetWebmailFlagResponse() {
        return new SetWebmailFlagResponse();
    }

    /**
     * Create an instance of {@link RemoveWebmailFlagRequest }
     * 
     */
    public RemoveWebmailFlagRequest createRemoveWebmailFlagRequest() {
        return new RemoveWebmailFlagRequest();
    }

    /**
     * Create an instance of {@link RemoveWebmailFlagResponse }
     * 
     */
    public RemoveWebmailFlagResponse createRemoveWebmailFlagResponse() {
        return new RemoveWebmailFlagResponse();
    }

    /**
     * Create an instance of {@link SetWebmailSeenRequest }
     * 
     */
    public SetWebmailSeenRequest createSetWebmailSeenRequest() {
        return new SetWebmailSeenRequest();
    }

    /**
     * Create an instance of {@link SetWebmailSeenResponse }
     * 
     */
    public SetWebmailSeenResponse createSetWebmailSeenResponse() {
        return new SetWebmailSeenResponse();
    }

    /**
     * Create an instance of {@link SetWebmailUnSeenRequest }
     * 
     */
    public SetWebmailUnSeenRequest createSetWebmailUnSeenRequest() {
        return new SetWebmailUnSeenRequest();
    }

    /**
     * Create an instance of {@link SetWebmailUnSeenResponse }
     * 
     */
    public SetWebmailUnSeenResponse createSetWebmailUnSeenResponse() {
        return new SetWebmailUnSeenResponse();
    }

    /**
     * Create an instance of {@link GetMailDisplayRequest }
     * 
     */
    public GetMailDisplayRequest createGetMailDisplayRequest() {
        return new GetMailDisplayRequest();
    }

    /**
     * Create an instance of {@link GetMailDisplayResponse }
     * 
     */
    public GetMailDisplayResponse createGetMailDisplayResponse() {
        return new GetMailDisplayResponse();
    }

    /**
     * Create an instance of {@link InboxDisplay }
     * 
     */
    public InboxDisplay createInboxDisplay() {
        return new InboxDisplay();
    }

    /**
     * Create an instance of {@link GetMailHeaderRequest }
     * 
     */
    public GetMailHeaderRequest createGetMailHeaderRequest() {
        return new GetMailHeaderRequest();
    }

    /**
     * Create an instance of {@link GetMailHeaderResponse }
     * 
     */
    public GetMailHeaderResponse createGetMailHeaderResponse() {
        return new GetMailHeaderResponse();
    }

    /**
     * Create an instance of {@link Attachment }
     * 
     */
    public Attachment createAttachment() {
        return new Attachment();
    }

    /**
     * Create an instance of {@link GetMailAttachDownloadRequest }
     * 
     */
    public GetMailAttachDownloadRequest createGetMailAttachDownloadRequest() {
        return new GetMailAttachDownloadRequest();
    }

    /**
     * Create an instance of {@link GetMailAttachDownloadResponse }
     * 
     */
    public GetMailAttachDownloadResponse createGetMailAttachDownloadResponse() {
        return new GetMailAttachDownloadResponse();
    }

    /**
     * Create an instance of {@link GetComposeMailRequest }
     * 
     */
    public GetComposeMailRequest createGetComposeMailRequest() {
        return new GetComposeMailRequest();
    }

    /**
     * Create an instance of {@link GetComposeMailResponse }
     * 
     */
    public GetComposeMailResponse createGetComposeMailResponse() {
        return new GetComposeMailResponse();
    }

    /**
     * Create an instance of {@link GetSaveMailDraftRequest }
     * 
     */
    public GetSaveMailDraftRequest createGetSaveMailDraftRequest() {
        return new GetSaveMailDraftRequest();
    }

    /**
     * Create an instance of {@link GetSaveMailDraftResponse }
     * 
     */
    public GetSaveMailDraftResponse createGetSaveMailDraftResponse() {
        return new GetSaveMailDraftResponse();
    }

    /**
     * Create an instance of {@link GetWebmailDeleteDraftRequest }
     * 
     */
    public GetWebmailDeleteDraftRequest createGetWebmailDeleteDraftRequest() {
        return new GetWebmailDeleteDraftRequest();
    }

    /**
     * Create an instance of {@link GetWebmailDeleteDraftResponse }
     * 
     */
    public GetWebmailDeleteDraftResponse createGetWebmailDeleteDraftResponse() {
        return new GetWebmailDeleteDraftResponse();
    }

    /**
     * Create an instance of {@link GetLdapModifyOneAttRequest }
     * 
     */
    public GetLdapModifyOneAttRequest createGetLdapModifyOneAttRequest() {
        return new GetLdapModifyOneAttRequest();
    }

    /**
     * Create an instance of {@link GetLdapModifyOneAttResponse }
     * 
     */
    public GetLdapModifyOneAttResponse createGetLdapModifyOneAttResponse() {
        return new GetLdapModifyOneAttResponse();
    }

    /**
     * Create an instance of {@link GetLdapModifyListAttRequest }
     * 
     */
    public GetLdapModifyListAttRequest createGetLdapModifyListAttRequest() {
        return new GetLdapModifyListAttRequest();
    }

    /**
     * Create an instance of {@link GetLdapModifyListAttResponse }
     * 
     */
    public GetLdapModifyListAttResponse createGetLdapModifyListAttResponse() {
        return new GetLdapModifyListAttResponse();
    }

    /**
     * Create an instance of {@link GetLdapUserDirectoryRequest }
     * 
     */
    public GetLdapUserDirectoryRequest createGetLdapUserDirectoryRequest() {
        return new GetLdapUserDirectoryRequest();
    }

    /**
     * Create an instance of {@link GetLdapUserDirectoryResponse }
     * 
     */
    public GetLdapUserDirectoryResponse createGetLdapUserDirectoryResponse() {
        return new GetLdapUserDirectoryResponse();
    }

    /**
     * Create an instance of {@link ArrayOfLdapUserDir }
     * 
     */
    public ArrayOfLdapUserDir createArrayOfLdapUserDir() {
        return new ArrayOfLdapUserDir();
    }

    /**
     * Create an instance of {@link LdapDirectory }
     * 
     */
    public LdapDirectory createLdapDirectory() {
        return new LdapDirectory();
    }

    /**
     * Create an instance of {@link CreateWorkspaceRequest }
     * 
     */
    public CreateWorkspaceRequest createCreateWorkspaceRequest() {
        return new CreateWorkspaceRequest();
    }

    /**
     * Create an instance of {@link CreateWorkspaceResponse }
     * 
     */
    public CreateWorkspaceResponse createCreateWorkspaceResponse() {
        return new CreateWorkspaceResponse();
    }

    /**
     * Create an instance of {@link CreateEssentialFoldersRequest }
     * 
     */
    public CreateEssentialFoldersRequest createCreateEssentialFoldersRequest() {
        return new CreateEssentialFoldersRequest();
    }

    /**
     * Create an instance of {@link CreateEssentialFoldersResponse }
     * 
     */
    public CreateEssentialFoldersResponse createCreateEssentialFoldersResponse() {
        return new CreateEssentialFoldersResponse();
    }

    /**
     * Create an instance of {@link GetSharedFoldersRequest }
     * 
     */
    public GetSharedFoldersRequest createGetSharedFoldersRequest() {
        return new GetSharedFoldersRequest();
    }

    /**
     * Create an instance of {@link GetSharedFoldersResponse }
     * 
     */
    public GetSharedFoldersResponse createGetSharedFoldersResponse() {
        return new GetSharedFoldersResponse();
    }

    /**
     * Create an instance of {@link FolderListReturn }
     * 
     */
    public FolderListReturn createFolderListReturn() {
        return new FolderListReturn();
    }

    /**
     * Create an instance of {@link GetSharedFoldersByPathRequest }
     * 
     */
    public GetSharedFoldersByPathRequest createGetSharedFoldersByPathRequest() {
        return new GetSharedFoldersByPathRequest();
    }

    /**
     * Create an instance of {@link GetSharedFoldersByPathDAVRequest }
     * 
     */
    public GetSharedFoldersByPathDAVRequest createGetSharedFoldersByPathDAVRequest() {
        return new GetSharedFoldersByPathDAVRequest();
    }

    /**
     * Create an instance of {@link GetSharedFoldersByPathResponse }
     * 
     */
    public GetSharedFoldersByPathResponse createGetSharedFoldersByPathResponse() {
        return new GetSharedFoldersByPathResponse();
    }

    /**
     * Create an instance of {@link GetRecycledDocsRequest }
     * 
     */
    public GetRecycledDocsRequest createGetRecycledDocsRequest() {
        return new GetRecycledDocsRequest();
    }

    /**
     * Create an instance of {@link GetRecycledDocsResponse }
     * 
     */
    public GetRecycledDocsResponse createGetRecycledDocsResponse() {
        return new GetRecycledDocsResponse();
    }

    /**
     * Create an instance of {@link FilesAndFolders }
     * 
     */
    public FilesAndFolders createFilesAndFolders() {
        return new FilesAndFolders();
    }

    /**
     * Create an instance of {@link GetFolderRequest }
     * 
     */
    public GetFolderRequest createGetFolderRequest() {
        return new GetFolderRequest();
    }

    /**
     * Create an instance of {@link GetFolderDAVRequest }
     * 
     */
    public GetFolderDAVRequest createGetFolderDAVRequest() {
        return new GetFolderDAVRequest();
    }

    /**
     * Create an instance of {@link GetFolderResponse }
     * 
     */
    public GetFolderResponse createGetFolderResponse() {
        return new GetFolderResponse();
    }

    /**
     * Create an instance of {@link HasChildRequest }
     * 
     */
    public HasChildRequest createHasChildRequest() {
        return new HasChildRequest();
    }

    /**
     * Create an instance of {@link HasChildResponse }
     * 
     */
    public HasChildResponse createHasChildResponse() {
        return new HasChildResponse();
    }

    /**
     * Create an instance of {@link CreateFolderRequest }
     * 
     */
    public CreateFolderRequest createCreateFolderRequest() {
        return new CreateFolderRequest();
    }

    /**
     * Create an instance of {@link CreateFolderDAVRequest }
     * 
     */
    public CreateFolderDAVRequest createCreateFolderDAVRequest() {
        return new CreateFolderDAVRequest();
    }

    /**
     * Create an instance of {@link CreateFolderResponse }
     * 
     */
    public CreateFolderResponse createCreateFolderResponse() {
        return new CreateFolderResponse();
    }

    /**
     * Create an instance of {@link Folder }
     * 
     */
    public Folder createFolder() {
        return new Folder();
    }

    /**
     * Create an instance of {@link GetFolderByPathRequest }
     * 
     */
    public GetFolderByPathRequest createGetFolderByPathRequest() {
        return new GetFolderByPathRequest();
    }

    /**
     * Create an instance of {@link GetFolderByPathDAVRequest }
     * 
     */
    public GetFolderByPathDAVRequest createGetFolderByPathDAVRequest() {
        return new GetFolderByPathDAVRequest();
    }

    /**
     * Create an instance of {@link GetFolderByPathResponse }
     * 
     */
    public GetFolderByPathResponse createGetFolderByPathResponse() {
        return new GetFolderByPathResponse();
    }

    /**
     * Create an instance of {@link ShareFolderByPathRequest }
     * 
     */
    public ShareFolderByPathRequest createShareFolderByPathRequest() {
        return new ShareFolderByPathRequest();
    }

    /**
     * Create an instance of {@link ShareFolderByPathResponse }
     * 
     */
    public ShareFolderByPathResponse createShareFolderByPathResponse() {
        return new ShareFolderByPathResponse();
    }

    /**
     * Create an instance of {@link AssignSinglePermissionRequest }
     * 
     */
    public AssignSinglePermissionRequest createAssignSinglePermissionRequest() {
        return new AssignSinglePermissionRequest();
    }

    /**
     * Create an instance of {@link AssignSinglePermissionDAVRequest }
     * 
     */
    public AssignSinglePermissionDAVRequest createAssignSinglePermissionDAVRequest() {
        return new AssignSinglePermissionDAVRequest();
    }

    /**
     * Create an instance of {@link RemoveAssignedPermissionRequest }
     * 
     */
    public RemoveAssignedPermissionRequest createRemoveAssignedPermissionRequest() {
        return new RemoveAssignedPermissionRequest();
    }

    /**
     * Create an instance of {@link RemoveAssignedPermissionDAVRequest }
     * 
     */
    public RemoveAssignedPermissionDAVRequest createRemoveAssignedPermissionDAVRequest() {
        return new RemoveAssignedPermissionDAVRequest();
    }

    /**
     * Create an instance of {@link AssignSinglePermissionResponse }
     * 
     */
    public AssignSinglePermissionResponse createAssignSinglePermissionResponse() {
        return new AssignSinglePermissionResponse();
    }

    /**
     * Create an instance of {@link RemoveAssignedPermissionResponse }
     * 
     */
    public RemoveAssignedPermissionResponse createRemoveAssignedPermissionResponse() {
        return new RemoveAssignedPermissionResponse();
    }

    /**
     * Create an instance of {@link DeleteFolderRequest }
     * 
     */
    public DeleteFolderRequest createDeleteFolderRequest() {
        return new DeleteFolderRequest();
    }

    /**
     * Create an instance of {@link DeleteFolderResponse }
     * 
     */
    public DeleteFolderResponse createDeleteFolderResponse() {
        return new DeleteFolderResponse();
    }

    /**
     * Create an instance of {@link RecycleFolderRequest }
     * 
     */
    public RecycleFolderRequest createRecycleFolderRequest() {
        return new RecycleFolderRequest();
    }

    /**
     * Create an instance of {@link RecycleFolderDAVRequest }
     * 
     */
    public RecycleFolderDAVRequest createRecycleFolderDAVRequest() {
        return new RecycleFolderDAVRequest();
    }

    /**
     * Create an instance of {@link RecycleFolderResponse }
     * 
     */
    public RecycleFolderResponse createRecycleFolderResponse() {
        return new RecycleFolderResponse();
    }

    /**
     * Create an instance of {@link AddKeywordRequest }
     * 
     */
    public AddKeywordRequest createAddKeywordRequest() {
        return new AddKeywordRequest();
    }

    /**
     * Create an instance of {@link AddKeywordResponse }
     * 
     */
    public AddKeywordResponse createAddKeywordResponse() {
        return new AddKeywordResponse();
    }

    /**
     * Create an instance of {@link AddNotesRequest }
     * 
     */
    public AddNotesRequest createAddNotesRequest() {
        return new AddNotesRequest();
    }

    /**
     * Create an instance of {@link AddNotesResponse }
     * 
     */
    public AddNotesResponse createAddNotesResponse() {
        return new AddNotesResponse();
    }

    /**
     * Create an instance of {@link RemoveKeywordRequest }
     * 
     */
    public RemoveKeywordRequest createRemoveKeywordRequest() {
        return new RemoveKeywordRequest();
    }

    /**
     * Create an instance of {@link RemoveKeywordResponse }
     * 
     */
    public RemoveKeywordResponse createRemoveKeywordResponse() {
        return new RemoveKeywordResponse();
    }

    /**
     * Create an instance of {@link EditKeywordRequest }
     * 
     */
    public EditKeywordRequest createEditKeywordRequest() {
        return new EditKeywordRequest();
    }

    /**
     * Create an instance of {@link EditKeywordResponse }
     * 
     */
    public EditKeywordResponse createEditKeywordResponse() {
        return new EditKeywordResponse();
    }

    /**
     * Create an instance of {@link RemoveNotesRequest }
     * 
     */
    public RemoveNotesRequest createRemoveNotesRequest() {
        return new RemoveNotesRequest();
    }

    /**
     * Create an instance of {@link RemoveNotesResponse }
     * 
     */
    public RemoveNotesResponse createRemoveNotesResponse() {
        return new RemoveNotesResponse();
    }

    /**
     * Create an instance of {@link RestoreFolderRequest }
     * 
     */
    public RestoreFolderRequest createRestoreFolderRequest() {
        return new RestoreFolderRequest();
    }

    /**
     * Create an instance of {@link RestoreFolderResponse }
     * 
     */
    public RestoreFolderResponse createRestoreFolderResponse() {
        return new RestoreFolderResponse();
    }

    /**
     * Create an instance of {@link RestoreVersionRequest }
     * 
     */
    public RestoreVersionRequest createRestoreVersionRequest() {
        return new RestoreVersionRequest();
    }

    /**
     * Create an instance of {@link RestoreVersionResponse }
     * 
     */
    public RestoreVersionResponse createRestoreVersionResponse() {
        return new RestoreVersionResponse();
    }

    /**
     * Create an instance of {@link RecentlyModifiedRequest }
     * 
     */
    public RecentlyModifiedRequest createRecentlyModifiedRequest() {
        return new RecentlyModifiedRequest();
    }

    /**
     * Create an instance of {@link RecentlyModifiedResponse }
     * 
     */
    public RecentlyModifiedResponse createRecentlyModifiedResponse() {
        return new RecentlyModifiedResponse();
    }

    /**
     * Create an instance of {@link RenameFolderRequest }
     * 
     */
    public RenameFolderRequest createRenameFolderRequest() {
        return new RenameFolderRequest();
    }

    /**
     * Create an instance of {@link RenameFolderResponse }
     * 
     */
    public RenameFolderResponse createRenameFolderResponse() {
        return new RenameFolderResponse();
    }

    /**
     * Create an instance of {@link RenameFolderRes }
     * 
     */
    public RenameFolderRes createRenameFolderRes() {
        return new RenameFolderRes();
    }

    /**
     * Create an instance of {@link SearchDocByLikeRequest }
     * 
     */
    public SearchDocByLikeRequest createSearchDocByLikeRequest() {
        return new SearchDocByLikeRequest();
    }

    /**
     * Create an instance of {@link SearchDocByLikeResponse }
     * 
     */
    public SearchDocByLikeResponse createSearchDocByLikeResponse() {
        return new SearchDocByLikeResponse();
    }

    /**
     * Create an instance of {@link SearchDocByDateRequest }
     * 
     */
    public SearchDocByDateRequest createSearchDocByDateRequest() {
        return new SearchDocByDateRequest();
    }

    /**
     * Create an instance of {@link SearchDocByDateResponse }
     * 
     */
    public SearchDocByDateResponse createSearchDocByDateResponse() {
        return new SearchDocByDateResponse();
    }

    /**
     * Create an instance of {@link GetSharedFilesRequest }
     * 
     */
    public GetSharedFilesRequest createGetSharedFilesRequest() {
        return new GetSharedFilesRequest();
    }

    /**
     * Create an instance of {@link GetSharedFilesResponse }
     * 
     */
    public GetSharedFilesResponse createGetSharedFilesResponse() {
        return new GetSharedFilesResponse();
    }

    /**
     * Create an instance of {@link FileListReturn }
     * 
     */
    public FileListReturn createFileListReturn() {
        return new FileListReturn();
    }

    /**
     * Create an instance of {@link GetSharedFilesByPathRequest }
     * 
     */
    public GetSharedFilesByPathRequest createGetSharedFilesByPathRequest() {
        return new GetSharedFilesByPathRequest();
    }

    /**
     * Create an instance of {@link GetSharedFilesByPathResponse }
     * 
     */
    public GetSharedFilesByPathResponse createGetSharedFilesByPathResponse() {
        return new GetSharedFilesByPathResponse();
    }

    /**
     * Create an instance of {@link GetSharedFilesByPathWithContentRequest }
     * 
     */
    public GetSharedFilesByPathWithContentRequest createGetSharedFilesByPathWithContentRequest() {
        return new GetSharedFilesByPathWithContentRequest();
    }

    /**
     * Create an instance of {@link GetSharedFilesByPathWithContentDAVRequest }
     * 
     */
    public GetSharedFilesByPathWithContentDAVRequest createGetSharedFilesByPathWithContentDAVRequest() {
        return new GetSharedFilesByPathWithContentDAVRequest();
    }

    /**
     * Create an instance of {@link GetSharedFilesByPathWithContentResponse }
     * 
     */
    public GetSharedFilesByPathWithContentResponse createGetSharedFilesByPathWithContentResponse() {
        return new GetSharedFilesByPathWithContentResponse();
    }

    /**
     * Create an instance of {@link GetSharedFilesWithOutStreamRequest }
     * 
     */
    public GetSharedFilesWithOutStreamRequest createGetSharedFilesWithOutStreamRequest() {
        return new GetSharedFilesWithOutStreamRequest();
    }

    /**
     * Create an instance of {@link GetSharedFilesWithOutStreamResponse }
     * 
     */
    public GetSharedFilesWithOutStreamResponse createGetSharedFilesWithOutStreamResponse() {
        return new GetSharedFilesWithOutStreamResponse();
    }

    /**
     * Create an instance of {@link GetSharedFilesByPathWithOutStreamRequest }
     * 
     */
    public GetSharedFilesByPathWithOutStreamRequest createGetSharedFilesByPathWithOutStreamRequest() {
        return new GetSharedFilesByPathWithOutStreamRequest();
    }

    /**
     * Create an instance of {@link GetSharedFilesByPathWithOutStreamResponse }
     * 
     */
    public GetSharedFilesByPathWithOutStreamResponse createGetSharedFilesByPathWithOutStreamResponse() {
        return new GetSharedFilesByPathWithOutStreamResponse();
    }

    /**
     * Create an instance of {@link GetFileRequest }
     * 
     */
    public GetFileRequest createGetFileRequest() {
        return new GetFileRequest();
    }

    /**
     * Create an instance of {@link GetFileDAVRequest }
     * 
     */
    public GetFileDAVRequest createGetFileDAVRequest() {
        return new GetFileDAVRequest();
    }

    /**
     * Create an instance of {@link GetFileResponse }
     * 
     */
    public GetFileResponse createGetFileResponse() {
        return new GetFileResponse();
    }

    /**
     * Create an instance of {@link GetFileWithOutStreamRequest }
     * 
     */
    public GetFileWithOutStreamRequest createGetFileWithOutStreamRequest() {
        return new GetFileWithOutStreamRequest();
    }

    /**
     * Create an instance of {@link GetFileWithOutStreamDAVRequest }
     * 
     */
    public GetFileWithOutStreamDAVRequest createGetFileWithOutStreamDAVRequest() {
        return new GetFileWithOutStreamDAVRequest();
    }

    /**
     * Create an instance of {@link GetFileWithOutStreamResponse }
     * 
     */
    public GetFileWithOutStreamResponse createGetFileWithOutStreamResponse() {
        return new GetFileWithOutStreamResponse();
    }

    /**
     * Create an instance of {@link CreateFileRequest }
     * 
     */
    public CreateFileRequest createCreateFileRequest() {
        return new CreateFileRequest();
    }

    /**
     * Create an instance of {@link CreateFileDAVRequest }
     * 
     */
    public CreateFileDAVRequest createCreateFileDAVRequest() {
        return new CreateFileDAVRequest();
    }

    /**
     * Create an instance of {@link CreateFileResponse }
     * 
     */
    public CreateFileResponse createCreateFileResponse() {
        return new CreateFileResponse();
    }

    /**
     * Create an instance of {@link File }
     * 
     */
    public File createFile() {
        return new File();
    }

    /**
     * Create an instance of {@link GetFileByPathRequest }
     * 
     */
    public GetFileByPathRequest createGetFileByPathRequest() {
        return new GetFileByPathRequest();
    }

    /**
     * Create an instance of {@link GetFileByPathDAVRequest }
     * 
     */
    public GetFileByPathDAVRequest createGetFileByPathDAVRequest() {
        return new GetFileByPathDAVRequest();
    }

    /**
     * Create an instance of {@link GetFileByPathResponse }
     * 
     */
    public GetFileByPathResponse createGetFileByPathResponse() {
        return new GetFileByPathResponse();
    }

    /**
     * Create an instance of {@link GetFileByPathWithOutStreamRequest }
     * 
     */
    public GetFileByPathWithOutStreamRequest createGetFileByPathWithOutStreamRequest() {
        return new GetFileByPathWithOutStreamRequest();
    }

    /**
     * Create an instance of {@link GetFileByPathWithOutStreamResponse }
     * 
     */
    public GetFileByPathWithOutStreamResponse createGetFileByPathWithOutStreamResponse() {
        return new GetFileByPathWithOutStreamResponse();
    }

    /**
     * Create an instance of {@link ShareFileByPathRequest }
     * 
     */
    public ShareFileByPathRequest createShareFileByPathRequest() {
        return new ShareFileByPathRequest();
    }

    /**
     * Create an instance of {@link ShareFileByPathResponse }
     * 
     */
    public ShareFileByPathResponse createShareFileByPathResponse() {
        return new ShareFileByPathResponse();
    }

    /**
     * Create an instance of {@link DeleteFileRequest }
     * 
     */
    public DeleteFileRequest createDeleteFileRequest() {
        return new DeleteFileRequest();
    }

    /**
     * Create an instance of {@link DeleteFileDAVRequest }
     * 
     */
    public DeleteFileDAVRequest createDeleteFileDAVRequest() {
        return new DeleteFileDAVRequest();
    }

    /**
     * Create an instance of {@link DeleteFileResponse }
     * 
     */
    public DeleteFileResponse createDeleteFileResponse() {
        return new DeleteFileResponse();
    }

    /**
     * Create an instance of {@link RecycleFileRequest }
     * 
     */
    public RecycleFileRequest createRecycleFileRequest() {
        return new RecycleFileRequest();
    }

    /**
     * Create an instance of {@link RecycleFileResponse }
     * 
     */
    public RecycleFileResponse createRecycleFileResponse() {
        return new RecycleFileResponse();
    }

    /**
     * Create an instance of {@link RestoreFileRequest }
     * 
     */
    public RestoreFileRequest createRestoreFileRequest() {
        return new RestoreFileRequest();
    }

    /**
     * Create an instance of {@link RestoreFileResponse }
     * 
     */
    public RestoreFileResponse createRestoreFileResponse() {
        return new RestoreFileResponse();
    }

    /**
     * Create an instance of {@link RenameFileRequest }
     * 
     */
    public RenameFileRequest createRenameFileRequest() {
        return new RenameFileRequest();
    }

    /**
     * Create an instance of {@link RenameFileResponse }
     * 
     */
    public RenameFileResponse createRenameFileResponse() {
        return new RenameFileResponse();
    }

    /**
     * Create an instance of {@link RenameFileRes }
     * 
     */
    public RenameFileRes createRenameFileRes() {
        return new RenameFileRes();
    }

    /**
     * Create an instance of {@link EditFileRequest }
     * 
     */
    public EditFileRequest createEditFileRequest() {
        return new EditFileRequest();
    }

    /**
     * Create an instance of {@link EditFileDAVRequest }
     * 
     */
    public EditFileDAVRequest createEditFileDAVRequest() {
        return new EditFileDAVRequest();
    }

    /**
     * Create an instance of {@link EditFileResponse }
     * 
     */
    public EditFileResponse createEditFileResponse() {
        return new EditFileResponse();
    }

    /**
     * Create an instance of {@link EditFileRes }
     * 
     */
    public EditFileRes createEditFileRes() {
        return new EditFileRes();
    }

    /**
     * Create an instance of {@link SortByPropertyRequest }
     * 
     */
    public SortByPropertyRequest createSortByPropertyRequest() {
        return new SortByPropertyRequest();
    }

    /**
     * Create an instance of {@link SortByPropertyResponse }
     * 
     */
    public SortByPropertyResponse createSortByPropertyResponse() {
        return new SortByPropertyResponse();
    }

    /**
     * Create an instance of {@link SortByPropertyRes }
     * 
     */
    public SortByPropertyRes createSortByPropertyRes() {
        return new SortByPropertyRes();
    }

    /**
     * Create an instance of {@link GetVCFFileRequest }
     * 
     */
    public GetVCFFileRequest createGetVCFFileRequest() {
        return new GetVCFFileRequest();
    }

    /**
     * Create an instance of {@link GetVCFFileDAVRequest }
     * 
     */
    public GetVCFFileDAVRequest createGetVCFFileDAVRequest() {
        return new GetVCFFileDAVRequest();
    }

    /**
     * Create an instance of {@link GetVCFFileResponse }
     * 
     */
    public GetVCFFileResponse createGetVCFFileResponse() {
        return new GetVCFFileResponse();
    }

    /**
     * Create an instance of {@link VCFFileListReturn }
     * 
     */
    public VCFFileListReturn createVCFFileListReturn() {
        return new VCFFileListReturn();
    }

    /**
     * Create an instance of {@link MoveDocRequest }
     * 
     */
    public MoveDocRequest createMoveDocRequest() {
        return new MoveDocRequest();
    }

    /**
     * Create an instance of {@link MoveDocResponse }
     * 
     */
    public MoveDocResponse createMoveDocResponse() {
        return new MoveDocResponse();
    }

    /**
     * Create an instance of {@link CopyDocRequest }
     * 
     */
    public CopyDocRequest createCopyDocRequest() {
        return new CopyDocRequest();
    }

    /**
     * Create an instance of {@link CopyDocResponse }
     * 
     */
    public CopyDocResponse createCopyDocResponse() {
        return new CopyDocResponse();
    }

    /**
     * Create an instance of {@link SetSortOrderRequest }
     * 
     */
    public SetSortOrderRequest createSetSortOrderRequest() {
        return new SetSortOrderRequest();
    }

    /**
     * Create an instance of {@link SetSortOrderResponse }
     * 
     */
    public SetSortOrderResponse createSetSortOrderResponse() {
        return new SetSortOrderResponse();
    }

    /**
     * Create an instance of {@link CheckDocExistRequest }
     * 
     */
    public CheckDocExistRequest createCheckDocExistRequest() {
        return new CheckDocExistRequest();
    }

    /**
     * Create an instance of {@link CheckDocExistResponse }
     * 
     */
    public CheckDocExistResponse createCheckDocExistResponse() {
        return new CheckDocExistResponse();
    }

    /**
     * Create an instance of {@link ArrayOfFolders }
     * 
     */
    public ArrayOfFolders createArrayOfFolders() {
        return new ArrayOfFolders();
    }

    /**
     * Create an instance of {@link FolderVersionDetail }
     * 
     */
    public FolderVersionDetail createFolderVersionDetail() {
        return new FolderVersionDetail();
    }

    /**
     * Create an instance of {@link ArrayOfFiles }
     * 
     */
    public ArrayOfFiles createArrayOfFiles() {
        return new ArrayOfFiles();
    }

    /**
     * Create an instance of {@link FileVersionDetail }
     * 
     */
    public FileVersionDetail createFileVersionDetail() {
        return new FileVersionDetail();
    }

    /**
     * Create an instance of {@link ArrayOfVCFFiles }
     * 
     */
    public ArrayOfVCFFiles createArrayOfVCFFiles() {
        return new ArrayOfVCFFiles();
    }

    /**
     * Create an instance of {@link VCFFileAtt }
     * 
     */
    public VCFFileAtt createVCFFileAtt() {
        return new VCFFileAtt();
    }

}
