//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.31 at 05:59:11 PM IST 
//


package webmail.wsdlnew;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SetWebmailUnSeenStatus" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "setWebmailUnSeenStatus"
})
@XmlRootElement(name = "setWebmailUnSeenResponse", namespace = "http://webmail.com/Seenaction")
public class SetWebmailUnSeenResponse {

    @XmlElement(name = "SetWebmailUnSeenStatus", namespace = "http://webmail.com/Seenaction")
    protected boolean setWebmailUnSeenStatus;

    /**
     * Gets the value of the setWebmailUnSeenStatus property.
     * 
     */
    public boolean isSetWebmailUnSeenStatus() {
        return setWebmailUnSeenStatus;
    }

    /**
     * Sets the value of the setWebmailUnSeenStatus property.
     * 
     */
    public void setSetWebmailUnSeenStatus(boolean value) {
        this.setWebmailUnSeenStatus = value;
    }

}
