//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.13 at 11:39:55 AM IST 
//


package webmail.wsdlcal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="response" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="eventuid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="eventcolor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="repeatdates" type="{http://webmail.com/calendar}DateTimeList"/>
 *         &lt;element name="updateStatus" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "response",
    "eventuid",
    "eventcolor",
    "repeatdates",
    "updateStatus"
})
@XmlRootElement(name = "createEventResponse")
public class CreateEventResponse {

    @XmlElement(required = true)
    protected byte[] response;
    @XmlElement(required = true)
    protected String eventuid;
    @XmlElement(required = true)
    protected String eventcolor;
    @XmlElement(required = true)
    protected DateTimeList repeatdates;
    protected boolean updateStatus;

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setResponse(byte[] value) {
        this.response = value;
    }

    /**
     * Gets the value of the eventuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventuid() {
        return eventuid;
    }

    /**
     * Sets the value of the eventuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventuid(String value) {
        this.eventuid = value;
    }

    /**
     * Gets the value of the eventcolor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventcolor() {
        return eventcolor;
    }

    /**
     * Sets the value of the eventcolor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventcolor(String value) {
        this.eventcolor = value;
    }

    /**
     * Gets the value of the repeatdates property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeList }
     *     
     */
    public DateTimeList getRepeatdates() {
        return repeatdates;
    }

    /**
     * Sets the value of the repeatdates property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeList }
     *     
     */
    public void setRepeatdates(DateTimeList value) {
        this.repeatdates = value;
    }

    /**
     * Gets the value of the updateStatus property.
     * 
     */
    public boolean isUpdateStatus() {
        return updateStatus;
    }

    /**
     * Sets the value of the updateStatus property.
     * 
     */
    public void setUpdateStatus(boolean value) {
        this.updateStatus = value;
    }

}
