//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.13 at 11:39:55 AM IST 
//


package webmail.wsdlcal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CalID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CalColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CalMethod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="permission" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "calID",
    "calColor",
    "calMethod",
    "userid",
    "permission"
})
@XmlRootElement(name = "createCalendarRequest")
public class CreateCalendarRequest {

    @XmlElement(name = "CalID", required = true)
    protected String calID;
    @XmlElement(name = "CalColor", required = true)
    protected String calColor;
    @XmlElement(name = "CalMethod", required = true)
    protected String calMethod;
    @XmlElement(required = true)
    protected String userid;
    @XmlElement(required = true)
    protected String permission;

    /**
     * Gets the value of the calID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalID() {
        return calID;
    }

    /**
     * Sets the value of the calID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalID(String value) {
        this.calID = value;
    }

    /**
     * Gets the value of the calColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalColor() {
        return calColor;
    }

    /**
     * Sets the value of the calColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalColor(String value) {
        this.calColor = value;
    }

    /**
     * Gets the value of the calMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalMethod() {
        return calMethod;
    }

    /**
     * Sets the value of the calMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalMethod(String value) {
        this.calMethod = value;
    }

    /**
     * Gets the value of the userid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserid() {
        return userid;
    }

    /**
     * Sets the value of the userid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserid(String value) {
        this.userid = value;
    }

    /**
     * Gets the value of the permission property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPermission() {
        return permission;
    }

    /**
     * Sets the value of the permission property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPermission(String value) {
        this.permission = value;
    }

}
