//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.13 at 11:39:55 AM IST 
//


package webmail.wsdlcal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="newCalendar" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="existingCalendar" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "newCalendar",
    "existingCalendar"
})
@XmlRootElement(name = "getImportCalendarRequest")
public class GetImportCalendarRequest {

    @XmlElement(required = true)
    protected byte[] newCalendar;
    @XmlElement(required = true)
    protected byte[] existingCalendar;

    /**
     * Gets the value of the newCalendar property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getNewCalendar() {
        return newCalendar;
    }

    /**
     * Sets the value of the newCalendar property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setNewCalendar(byte[] value) {
        this.newCalendar = value;
    }

    /**
     * Gets the value of the existingCalendar property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getExistingCalendar() {
        return existingCalendar;
    }

    /**
     * Sets the value of the existingCalendar property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setExistingCalendar(byte[] value) {
        this.existingCalendar = value;
    }

}
