//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.13 at 11:39:55 AM IST 
//


package webmail.wsdlcal;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.webmail.calendar package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.webmail.calendar
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GeteventdetailsResponse }
     * 
     */
    public GeteventdetailsResponse createGeteventdetailsResponse() {
        return new GeteventdetailsResponse();
    }

    /**
     * Create an instance of {@link EventBean }
     * 
     */
    public EventBean createEventBean() {
        return new EventBean();
    }

    /**
     * Create an instance of {@link CreateEventRequest }
     * 
     */
    public CreateEventRequest createCreateEventRequest() {
        return new CreateEventRequest();
    }

    /**
     * Create an instance of {@link GeteventdetailsRequest }
     * 
     */
    public GeteventdetailsRequest createGeteventdetailsRequest() {
        return new GeteventdetailsRequest();
    }

    /**
     * Create an instance of {@link GetFilterEventsResponse }
     * 
     */
    public GetFilterEventsResponse createGetFilterEventsResponse() {
        return new GetFilterEventsResponse();
    }

    /**
     * Create an instance of {@link EventArray }
     * 
     */
    public EventArray createEventArray() {
        return new EventArray();
    }

    /**
     * Create an instance of {@link GetFilterEventsRequest }
     * 
     */
    public GetFilterEventsRequest createGetFilterEventsRequest() {
        return new GetFilterEventsRequest();
    }

    /**
     * Create an instance of {@link GetInviteEventResponse }
     * 
     */
    public GetInviteEventResponse createGetInviteEventResponse() {
        return new GetInviteEventResponse();
    }

    /**
     * Create an instance of {@link GetInviteEventRequest }
     * 
     */
    public GetInviteEventRequest createGetInviteEventRequest() {
        return new GetInviteEventRequest();
    }

    /**
     * Create an instance of {@link GetEventsResponse }
     * 
     */
    public GetEventsResponse createGetEventsResponse() {
        return new GetEventsResponse();
    }

    /**
     * Create an instance of {@link GetDeleteEventResponse }
     * 
     */
    public GetDeleteEventResponse createGetDeleteEventResponse() {
        return new GetDeleteEventResponse();
    }

    /**
     * Create an instance of {@link GetImportCalendarResponse }
     * 
     */
    public GetImportCalendarResponse createGetImportCalendarResponse() {
        return new GetImportCalendarResponse();
    }

    /**
     * Create an instance of {@link ChangeColorResponse }
     * 
     */
    public ChangeColorResponse createChangeColorResponse() {
        return new ChangeColorResponse();
    }

    /**
     * Create an instance of {@link CreateEventResponse }
     * 
     */
    public CreateEventResponse createCreateEventResponse() {
        return new CreateEventResponse();
    }

    /**
     * Create an instance of {@link DateTimeList }
     * 
     */
    public DateTimeList createDateTimeList() {
        return new DateTimeList();
    }

    /**
     * Create an instance of {@link CreateCalendarRequest }
     * 
     */
    public CreateCalendarRequest createCreateCalendarRequest() {
        return new CreateCalendarRequest();
    }

    /**
     * Create an instance of {@link ImportCalendarRequest }
     * 
     */
    public ImportCalendarRequest createImportCalendarRequest() {
        return new ImportCalendarRequest();
    }

    /**
     * Create an instance of {@link GetEventsRequest }
     * 
     */
    public GetEventsRequest createGetEventsRequest() {
        return new GetEventsRequest();
    }

    /**
     * Create an instance of {@link GetCalendarDetailRequest }
     * 
     */
    public GetCalendarDetailRequest createGetCalendarDetailRequest() {
        return new GetCalendarDetailRequest();
    }

    /**
     * Create an instance of {@link GetImportCalendarRequest }
     * 
     */
    public GetImportCalendarRequest createGetImportCalendarRequest() {
        return new GetImportCalendarRequest();
    }

    /**
     * Create an instance of {@link GetCalendarMailResponse }
     * 
     */
    public GetCalendarMailResponse createGetCalendarMailResponse() {
        return new GetCalendarMailResponse();
    }

    /**
     * Create an instance of {@link GetCalendarMailRequest }
     * 
     */
    public GetCalendarMailRequest createGetCalendarMailRequest() {
        return new GetCalendarMailRequest();
    }

    /**
     * Create an instance of {@link GetUpdateCalendarRequest }
     * 
     */
    public GetUpdateCalendarRequest createGetUpdateCalendarRequest() {
        return new GetUpdateCalendarRequest();
    }

    /**
     * Create an instance of {@link CalendarBean }
     * 
     */
    public CalendarBean createCalendarBean() {
        return new CalendarBean();
    }

    /**
     * Create an instance of {@link GetDeleteEventRequest }
     * 
     */
    public GetDeleteEventRequest createGetDeleteEventRequest() {
        return new GetDeleteEventRequest();
    }

    /**
     * Create an instance of {@link ChangeColorRequest }
     * 
     */
    public ChangeColorRequest createChangeColorRequest() {
        return new ChangeColorRequest();
    }

    /**
     * Create an instance of {@link GetCalendarDetailResponse }
     * 
     */
    public GetCalendarDetailResponse createGetCalendarDetailResponse() {
        return new GetCalendarDetailResponse();
    }

    /**
     * Create an instance of {@link GetUpdateCalendarResponse }
     * 
     */
    public GetUpdateCalendarResponse createGetUpdateCalendarResponse() {
        return new GetUpdateCalendarResponse();
    }

    /**
     * Create an instance of {@link CreateCalendarResponse }
     * 
     */
    public CreateCalendarResponse createCreateCalendarResponse() {
        return new CreateCalendarResponse();
    }

}
