//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.10 at 12:23:05 PM IST 
//


package webmail.wsdltask;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.webmail.task package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.webmail.task
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetTaskDetailRequest }
     * 
     */
    public GetTaskDetailRequest createGetTaskDetailRequest() {
        return new GetTaskDetailRequest();
    }

    /**
     * Create an instance of {@link GetTaskDetailResponse }
     * 
     */
    public GetTaskDetailResponse createGetTaskDetailResponse() {
        return new GetTaskDetailResponse();
    }

    /**
     * Create an instance of {@link TaskBean }
     * 
     */
    public TaskBean createTaskBean() {
        return new TaskBean();
    }

    /**
     * Create an instance of {@link DeleteSelectedTaskResponse }
     * 
     */
    public DeleteSelectedTaskResponse createDeleteSelectedTaskResponse() {
        return new DeleteSelectedTaskResponse();
    }

    /**
     * Create an instance of {@link GetAddTaskRequest }
     * 
     */
    public GetAddTaskRequest createGetAddTaskRequest() {
        return new GetAddTaskRequest();
    }

    /**
     * Create an instance of {@link GetTasksRequest }
     * 
     */
    public GetTasksRequest createGetTasksRequest() {
        return new GetTasksRequest();
    }

    /**
     * Create an instance of {@link GetUpdateTaskRequest }
     * 
     */
    public GetUpdateTaskRequest createGetUpdateTaskRequest() {
        return new GetUpdateTaskRequest();
    }

    /**
     * Create an instance of {@link GetTasksResponse }
     * 
     */
    public GetTasksResponse createGetTasksResponse() {
        return new GetTasksResponse();
    }

    /**
     * Create an instance of {@link TaskArray }
     * 
     */
    public TaskArray createTaskArray() {
        return new TaskArray();
    }

    /**
     * Create an instance of {@link GetUpdateTaskResponse }
     * 
     */
    public GetUpdateTaskResponse createGetUpdateTaskResponse() {
        return new GetUpdateTaskResponse();
    }

    /**
     * Create an instance of {@link DateTimeTaskList }
     * 
     */
    public DateTimeTaskList createDateTimeTaskList() {
        return new DateTimeTaskList();
    }

    /**
     * Create an instance of {@link DeleteTaskResponse }
     * 
     */
    public DeleteTaskResponse createDeleteTaskResponse() {
        return new DeleteTaskResponse();
    }

    /**
     * Create an instance of {@link DeleteSelectedTaskRequest }
     * 
     */
    public DeleteSelectedTaskRequest createDeleteSelectedTaskRequest() {
        return new DeleteSelectedTaskRequest();
    }

    /**
     * Create an instance of {@link DeleteTaskRequest }
     * 
     */
    public DeleteTaskRequest createDeleteTaskRequest() {
        return new DeleteTaskRequest();
    }

    /**
     * Create an instance of {@link GetAddTaskResponse }
     * 
     */
    public GetAddTaskResponse createGetAddTaskResponse() {
        return new GetAddTaskResponse();
    }

}
